name: cocinagame
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  iconify_flutter: ^0.0.7
  http: ^1.2.2
  font_awesome_flutter: ^10.6.0
  phosphor_flutter: ^2.0.1
  ming_cute_icons: ^0.0.7
  solar_icons: ^0.0.5
  diacritic: ^0.1.3
  shared_preferences: ^2.2.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo_cocina2.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
